# Generated by Django 4.2.4 on 2023-08-25 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asambeni', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='takes_learners',
            field=models.CharField(default='Vosloorus', max_length=50),
        ),
        migrations.AddField(
            model_name='driver',
            name='to_area',
            field=models.CharField(default='Germiston', max_length=50),
        ),
    ]
