# Generated by Django 4.2.4 on 2023-08-25 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asambeni', '0002_driver_takes_learners_driver_to_area'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='takes_learners',
            new_name='takes_learners_from',
        ),
        migrations.RenameField(
            model_name='driver',
            old_name='to_area',
            new_name='to_school_area',
        ),
    ]
