# Generated by Django 4.2.4 on 2023-08-26 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asambeni', '0003_rename_takes_learners_driver_takes_learners_from_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaOfOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EndofOperationArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
