# Generated by Django 4.2.4 on 2023-08-26 01:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asambeni', '0004_areaofoperation_endofoperationarea'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='to_school_area',
            new_name='end_destination',
        ),
        migrations.RenameField(
            model_name='driver',
            old_name='takes_learners_from',
            new_name='start_destination',
        ),
        migrations.AlterField(
            model_name='areaofoperation',
            name='name',
            field=models.CharField(help_text='Enter your pick up point.', max_length=50, verbose_name='Pick Up Area'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='endofoperationarea',
            name='name',
            field=models.CharField(help_text='Enter your drop off point.', max_length=50, verbose_name='Drop Off Area'),
        ),
        migrations.AlterField(
            model_name='learner',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='learner_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
